server:
  port: 8008
  shutdown: graceful

spring:
  application:
    name: social-network-service
  jackson:
    serialization:
      indent_output: true
  profiles:
    include:
      - caffeine-config
      - web-config
  datasource:
    url: jdbc:mysql://localhost:3306/social_network?serverTimezone=UTC&characterEncoding=UTF-8
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


