springdoc:
  packages-to-scan: com.hmg.search.app.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    path: /
    disable-swagger-default-url: true
    defaultModelsExpandDepth: -1
    tags-sorter: alpha
  show-actuator: true

spring:
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      use-big-decimal-for-floats: true

swagger:
  base-url: http://localhost:8006

